DOW_MONDAY = "0"
DOW_TUESDAY = "1"
DOW_WEDNESDAY = "2"
DOW_THURSDAY = "3"
DOW_FRIDAY  = "4"
DOW_SATURDAY = "5"
DOW_SUNDAY = "6"


DAY_OF_WEEK_DICT = {
    DOW_MONDAY: '月',
    DOW_TUESDAY: '火',
    DOW_WEDNESDAY: '水',
    DOW_THURSDAY: '木',
    DOW_FRIDAY: '金',
    DOW_SATURDAY: '土',
    DOW_SUNDAY: '日'
}

TIME_FRAME_9_12 = "1"
TIME_FRAME_12_15 = "2"
TIME_FRAME_15_18 = "3"
TIME_FRAME_18_21 = "4"
TIME_FRAME_ANYTIME = "0"

TIME_FRAME_DICT = {
    TIME_FRAME_9_12: '9:00〜12:00',
    TIME_FRAME_12_15: '12:00〜15:00',
    TIME_FRAME_15_18: '15:00〜18:00',
    TIME_FRAME_18_21: '18:00〜21:00',
    TIME_FRAME_ANYTIME: '指定なし'
}
OPERATION_CHIRYO = "1"
OPERATION_TEIKI = "2"
OPERATION_WHITENING = "3"
OPERATION_KYOSEI = "4"
OPERATION_DICT = {
    OPERATION_CHIRYO: '治療',
    OPERATION_TEIKI: '定期検診・クリーニング',
    OPERATION_WHITENING: 'ホワイトニング',
    OPERATION_KYOSEI: '矯正'
}