# Generated by Django 2.1.5 on 2019-10-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='phone',
            field=models.CharField(default='080-0000-1111', max_length=100, verbose_name='電話番号'),
            preserve_default=False,
        ),
    ]
