# Generated by Django 2.2 on 2019-10-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='is_anytime',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
