# Generated by Django 2.1.5 on 2019-11-24 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicinvite',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2019, 11, 24, 8, 42, 24, 553469, tzinfo=utc), verbose_name='開始時間'),
        ),
    ]
