# Generated by Django 2.1.5 on 2019-11-27 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInviteAdditionalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='clinicadditionalfield',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicadditionalfieldoption',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.ClinicAdditionalField'),
        ),
        migrations.AddField(
            model_name='clinicinviteadditionalitem',
            name='chosen_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ClinicAdditionalFieldOption'),
        ),
        migrations.AddField(
            model_name='clinicinviteadditionalitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ClinicInvite'),
        ),
        migrations.AddField(
            model_name='clinicinviteadditionalitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ClinicAdditionalField'),
        ),
    ]
