# Generated by Django 2.1.5 on 2019-10-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clinic_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='qrcode',
            field=models.ImageField(null=True, upload_to='qrcode', verbose_name='QR'),
        ),
    ]
