# Generated by Django 2.1.5 on 2019-11-24 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191124_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicinvite',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='開始時間'),
        ),
    ]
