# Generated by Django 2.2 on 2019-10-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userentry_is_anytime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentry',
            old_name='is_whenever',
            new_name='is_anyday',
        ),
    ]
