# Generated by Django 2.2 on 2019-10-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191026_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='do_chiryo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userentry',
            name='do_kyousei',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userentry',
            name='do_teikikenshin',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userentry',
            name='do_whitening',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserEntryOperation',
        ),
    ]
