# Generated by Django 2.1.5 on 2019-11-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191124_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentry',
            name='do_chiryo',
        ),
        migrations.RemoveField(
            model_name='userentry',
            name='do_kyousei',
        ),
        migrations.RemoveField(
            model_name='userentry',
            name='do_teikikenshin',
        ),
        migrations.RemoveField(
            model_name='userentry',
            name='do_whitening',
        ),
    ]
